name: flutter_estd
description: Opinionated ESTD for Flutter projects.
version: 0.0.32
homepage: https://github.com/nyarian/flutter_estd

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.0.0
  collection: ^1.0.0
  rxdart: '>=0.0.0 <1.0.0'
  get_it: ^8.0.0
  shared_preferences: ^2.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
