name: flutter_estd
description: Opinionated ESTD for Flutter projects.
version: 0.0.1
homepage: https://github.com/nyarian/flutter_estd

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: any
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
